# Generated by Django 2.2.24 on 2022-03-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название по-русски')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название по-английски')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название по-японски')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='Изображение')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционировал')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Появился в')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Исчез в')),
                ('level', models.IntegerField(blank=True, default=50, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, default=50, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, default=50, null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, default=50, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, default=50, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
